config/routes.rb
Rails.application.routes.draw do

  
  ActiveAdmin.routes(self)

  put "/admin/users/:user.id/approve" => 'admin/users#approve', as: :admin_approve_user
  root "users#main_form"
  
  get '/auth/:provider/callback', to: 'sessions#create'

  get 'user/new' => 'users#new', as: :user_new

  post 'user' => 'users#create', as: :user_create
  
  get 'user/form' => 'users#main_form', as: :main_form

  get 'user/login' => 'sessions#new', as: :login_form

  post 'user/login_form' => 'sessions#create', as: :login_create

  get 'user/event_form/:user_id' => 'events#new', as: :event_new

  post 'user/event_create/:user_id' => 'events#create', as: :event_create

  get "event/:user_id/:event_id" => "events#delete", as: :event_destroy

  get 'log_out' => 'events#destroy', as: :log_out

  get 'edit/:user_id/:event_id' => 'events#edit', as: :event_edit

  get 'edit/:event_id' => 'events#show', as: :event_show

  put "edit/:user_id/:event_id" => "events#update", as: :event_update

  get "user/edit/:user_id" => "users#edit" , as: :user_edit

  put 'user/create/:user_id' => 'users#update', as: :user_update

  get 'user/show/:user_id' => 'users#show', as: :user_show

  get '/patient' => 'patients#new', as: :patient_new

  post '/patient' => 'patients#create', as: :patient_create

  get '/patient/:patient_id' => 'patients#show' , as: :patient_show

  post 'comment/create/:event_id' => 'comments#create', as: :comment_create

  get 'change/password/' => 'users#change_password', as: :change_password

  put 'update/password/' => 'users#password_update', as: :password_update

  get 'show/user/:user_id' => 'users#show_user', as: :show_user

end

app/views/partials/_event.html.erb
<div  ng-app="eventApp" ng-controller="eventController" >
<link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
<nav class="navbar navbar-default">
 <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.min.css" integrity="sha256-zV9aQFg2u+n7xs0FTQEhY0zGHSFlwgIu7pivQiwJ38E=" crossorigin="anonymous" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.min.js" integrity="sha256-xoE/2szqaiaaZh7goVyF5p9C/qBu9dM3V5utrQaiJMc=" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
  <script>
$(document).ready(function(){
    $('#purpose').on('change', function() {
      if ( this.value == '1')
      //.....................^.......
      {
        $("#business").show();
        $("#passing").hide();
        $("#personal").hide();

      }
      else if ( this.value == '2')
      {
        $("#passing").show();
        $("#personal").hide();
        $("#business").hide();

      }
      else if ( this.value == '0')
      {
        $("#personal").show();
         $("#business").hide();
        $("#passing").hide();
      }
      else
      {
        $("#personal").hide();
        $("#business").hide();
        $("#passing").hide();

      }
    });
});
</script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" integrity="sha256-rByPlHULObEjJ6XQxW/flG2r+22R5dKiAoef+aXWfik=" crossorigin="anonymous" />
<style type="text/css">
  .style{
    border-style: solid;
    padding: 15px;
  }
</style>
<%= include_gon %>

    <div class="container" >
      <div class="navbar-header">
        <a class="navbar-brand" href="#">
          <%= image_tag("logo.png")%><p style="font-family:'Pacifico',cursive;font-size:28px;">Events Schedule</p></a>
        </div>
        <ul class="nav navbar-nav navbar-right">

          <p class="active">

         
            <%= link_to "<button class=btn btn-success ng-click=capture()>Log out</button>".html_safe,log_out_path%>
            <%= link_to "<button class=btn btn-success>Profile</button>".html_safe,user_show_path%>
           
            <dir id="user_nav">
             <p style="font-size:18px"><b>logged in as</b></p><%= current_user.username%></br>
             <%= image_tag current_user.image, :style => "width:90px;heigth:90px"%>

</dir>
 </p>        
</ul>


   

          </div>  
        
      </nav>

app/views/partials/_signin.html.erb
<link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
<nav class="navbar navbar-default">
  <div class="container" >
    <div class="navbar-header">
    
          <%=link_to (image_tag("logo.png")),'/#'%>
          <p style="font-family:'Pacifico',cursive;font-size:28px;">Events Schedule</p>
    </div>
    <ul class="nav navbar-nav navbar-right">
   
     
      <li class="active">

      <li class="active">
       <li><%= link_to "<button class=btn btn-success>Not user? Sign up</button>".html_safe,user_new_path%>
      </li>
      <li>
        <%= link_to "Sign in with Twitter","/auth/twitter",id: "sign_in"%>
      </li>
       </ul>
       
  </div>
</nav>

app/views/partials/_signup.html.erb
<!DOCTYPE html>

<html lang="en" ng-app="eventApp" ng-controller="eventController"  >
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container" >
    <div class="navbar-header">
     
          <%=link_to (image_tag("logo.png")),'/#'%><p style="font-family:'Pacifico',cursive;font-size:28px;">Events Schedule</p>
    </div>
    <ul class="nav navbar-nav navbar-right">
     
     
      <li class="active">

      
      <li class="active">
      <li><%= link_to "<button class=btn btn-success>Main Page</button>".html_safe,root_url%>
      </li>
    
      
  </div>
</nav>