config/routes.rb
Rails.application.routes.draw do

  
  ActiveAdmin.routes(self)

  put "/admin/users/:user.id/approve" => 'admin/users#approve', as: :admin_approve_user
  root "users#main_form"
  
  get '/auth/:provider/callback', to: 'sessions#create'

  get 'user/new' => 'users#new', as: :user_new

  post 'user' => 'users#create', as: :user_create
  
  get 'user/form' => 'users#main_form', as: :main_form

  get 'user/login' => 'sessions#new', as: :login_form

  post 'user/login_form' => 'sessions#create', as: :login_create

  get 'user/event_form/:user_id' => 'events#new', as: :event_new

  post 'user/event_create/:user_id' => 'events#create', as: :event_create

  get "event/:user_id/:event_id" => "events#delete", as: :event_destroy

  get 'log_out' => 'events#destroy', as: :log_out

  get 'edit/:user_id/:event_id' => 'events#edit', as: :event_edit

  get 'edit/:event_id' => 'events#show', as: :event_show

  put "edit/:user_id/:event_id" => "events#update", as: :event_update

  get "user/edit/:user_id" => "users#edit" , as: :user_edit

  put 'user/create/:user_id' => 'users#update', as: :user_update

  get 'user/show/:user_id' => 'users#show', as: :user_show

  get '/patient' => 'patients#new', as: :patient_new

  post '/patient' => 'patients#create', as: :patient_create

  get '/patient/:patient_id' => 'patients#show' , as: :patient_show

  post 'comment/create/:event_id' => 'comments#create', as: :comment_create

  get 'change/password/' => 'users#change_password', as: :change_password

  put 'update/password/' => 'users#password_update', as: :password_update

  get 'show/user/:user_id' => 'users#show_user', as: :show_user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :trackable, :validatable
  # attr_accessible :email, :password, :password_confirmation
  has_many :invitations, foreign_key: :invitee_id
  has_many :events, through: :invitations
  attr_accessor :password
  before_save :encrypt_password
  validates_presence_of :firstname
  validates_presence_of :lastname
  validates_presence_of :username

  mount_uploader :image,ImageUploader

  validates_uniqueness_of :email
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_length_of :password, minimum: 6
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z]+\.)+[a-z]{2,})\z/i
  
  def self.create_with_omniauth(auth) 
    binding.pry
    create! do |user|                  
    user.provider = auth["provider"]    
    user.uid = auth.uid                 
    user.name = auth.info.name         
    user.save!                     
    end                  
  end

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	include UsersHelper
		def create
      @user = User.new(user_params)
      @user.image = params[:user][:images]
		  if (params[:user][:age] == "")
         @user.age = params[:age]
      else
        @user.age = params[:user][:age]
      end
        @user.save
      
      if @user.save
  			UserMailer.registration_confrimation(@user).deliver_now
      redirect_to user_new_path, :flash => { :success => "Mail has been sent to respective Email ID.Please follow the instrations as given." }
    		# redirect_to login_form_path, :flash => { :success => "Signed up" }
        
        # TDD
        # render json:{user:@user,status: 200}
  		else
       render "new"

       # TDD
        	# render json: {error: @user.errors.full_messages.first,status: 422, success: false, message: "Unsuccessfull in creating a user!"}
  		end
	end
	private

  	def user_params
   	 params.require(:user).permit(:firstname,:lastname,:username,:phone,:email,:password,:password_confirmation)
  	end
end

app/helpers/users_helper.rb
	module UsersHelper
	def main_form
		
	end
	def new
		@user=User.new
		@users=User.all
		@events=Event.all
		
		# render :json => @users
	end
	def show
		@user=User.find_by_id(params[:user_id])
		
	end
	def show_user
		
		@user=User.find_by_id(params[:user_id])
		
	end
	def index
		@users = User.all
	end

	def change_password
		current_user

	end

	def password_update
		@old_password = params[:user][:password]
		@new_password = params[:user][:password_new]
		old_password_hash = BCrypt::Engine.hash_secret(@old_password, current_user.password_salt)
		new_password_hash = BCrypt::Engine.hash_secret(@new_password, current_user.password_salt)
		if old_password_hash == current_user.password_hash
			user.update_attribute(:password, new_password_hash)
		else
			redirect_to change_password_path, :flash => { :success => "Invalid old password" }
		end


	end

	def edit
		# binding.pry
		@user=User.find_by_id(params[:user_id])
	end

	def update
		# binding.pry
		@user = User.find_by_id(params[:user_id])
		@user.update_attributes(user_params)
		redirect_to event_new_path, :flash => { :success => "Updated" }
	end
end

app/views/users/change_password.html.erb
<div class="container">
<%= form_for :user, url:password_update_path, method: :put do |f|%>

    <%= f.label :Old_password %>          <%= f.password_field :password,class: "form-control",:required =>true %></br></br>
    <%= f.label :New_password%>  <%= f.password_field :password_new,class: "form-control",:required =>true %></br></br>
          <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %></br>

 <%= f.submit :Submit,:class=>"btn" %>
  <%= link_to "<button class=btn btn-success>Back</button>".html_safe,user_edit_path(current_user.id)%></br>

 <%end%> 
 </div>

app/views/users/edit.html.erb
<link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
<nav class="navbar navbar-default">
 <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.min.css" integrity="sha256-zV9aQFg2u+n7xs0FTQEhY0zGHSFlwgIu7pivQiwJ38E=" crossorigin="anonymous" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.min.js" integrity="sha256-xoE/2szqaiaaZh7goVyF5p9C/qBu9dM3V5utrQaiJMc=" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
    <div class="container" >
      <div class="navbar-header">
        <a class="navbar-brand" href="#">
          <%= image_tag("logo.png")%><p style="font-family:'Pacifico',cursive;font-size:28px;">Events Schedule</p></a>
        </div>
        <ul class="nav navbar-nav navbar-right">

          <p class="active">
            
            <%= link_to "<button class=btn btn-success ng-click=capture()>Log out</button>".html_safe,log_out_path%>
            
           
            <dir id="user_nav">
             <p style="font-size:18px"><b>logged in as</b></p><%= current_user.username%>
</dir>
 </p>        
</ul>
          

          </div>  
        
      </nav>

<%= form_for @user, url:user_update_path, method: :put do |f|%>

</br></br>

  <div style="font-size:18px;">
  
  <div class="container">
  <h1 style="text-align:center">Profile</h1></br>
 <div class="row">
 <div class="col-sm-4">
 </div>
 <div class="col-sm-5">
      <%= f.label "Enter First name" %>    <%= f.text_field :firstname , class: "form-control",required: true%></br></br>
    <%= f.label :Enter_Last_name%>       <%= f.text_field :lastname , class: "form-control",:required=>true %></br></br>
    <%= f.label :Enter_User_name%>       <%= f.text_field :username, class: "form-control",:required=>true%></br></br>
    <%= f.label :Enter_valid_Email %>           <%= f.email_field :email, class: "form-control",:required=>true %></br></br>
    <%= f.label :Enter_Ph_number%>    <%= f.text_field :phone,class: "form-control",:required=>true %></br></br>
  <%= f.submit :Submit,:class=>"btn" %>
  <%= link_to "<button class=btn btn-success>Cancel</button>".html_safe,event_new_path%>
  <%= link_to "<button class=btn btn-success>Change password</button>".html_safe,change_password_path%>

</div>
<div class="col-sm-3">
</div> 
</div>  

  </div>

<% end %>

app/views/users/main_form.html.erb
<link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
<nav class="navbar navbar-default">
  <div class="container" >
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
          <%= image_tag("logo.png")%><p style="font-family:'Pacifico',cursive;font-size:28px;">Events Schedule</p></a>
    </div>
    <ul class="nav navbar-nav navbar-right">
   
     
      <li class="active">
 
      <li><%= link_to "<button class=btn btn-success>Log in</button>".html_safe,login_form_path%>
      </li>
        <li><%= link_to "<button class=btn btn-success>Not user? Sign up</button>".html_safe,user_new_path%>
      </li>

       </ul>
       
  </div>
</nav>
</br>
</br>

<div class="container">
    <div class="jumbotron">
      <h1 style="font-family:'Pacifico',cursive; ">Events Schedule</h1>      
      <p>Invite your Invitees to your special Occasion</p>
    </div>
    <div class="row">
      <div class="col-sm-2">
      </div>
      <div class="col-sm-10">
        <%= image_tag("main.jpg") %>
      </div>
    </div>
</div> 

app/views/users/new.html.erb
<%= render 'partials/signup'%>
<%= form_for @user,url: user_create_path do |f| %>
</br></br>

  <div style="font-size:18px;">
  
  <div class="container">
  <h1 style="text-align:center">Sign Up</h1></br>
 <div class="row">
 <div class="col-sm-4">
 </div>
 <div class="col-sm-5">
      <%= f.label "Enter First name" %>    <%= f.text_field :firstname , class: "form-control",required: true%></br></br>
    <%= f.label :Enter_Last_name%>       <%= f.text_field :lastname , class: "form-control",:required=>true %></br></br>
    <%= f.label :Enter_User_name%>       <%= f.text_field :username, class: "form-control",:required=>true%></br></br>
    <%= f.label :Enter_valid_Email %>           <%= f.email_field :email, class: "form-control",:required=>true %></br></br>
    <%= f.label :Enter_Ph_number%>    <%= f.text_field :phone,class: "form-control",:required=>true %></br></br>
    <%= f.label :Select_age %> 
             
                <ul>
                 
                  <li>
                    <%= radio_button_tag :age, "20-40"%>20-40</br>
                    <%= radio_button_tag :age, '40+' %> > 40</br>
                   
                    <%= radio_button_tag :age,:type %> other
                    <%= f.text_field :age, :id => "text",:style => "display: none" %></br>

                  </li>
                  
                </ul>
    <%= f.label :Upload_Image%> <%= f.file_field :images %>
    <%= f.label :Enter_password %>              <%= f.password_field :password,class: "form-control", :ng => {:model => "password"},:required =>true %></br></br>
      <% if @user.errors.any? %>
    <div class="error_messages">
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.label :password_confirmation %>  <%= f.password_field :password_confirmation,class: "form-control",:ng => {:model => "confrim"},:required=>true %></br></br>
  
<% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %></br>
  <%= f.submit :Submit,:class=>"btn",:ng => {:disabled => "result"}  %>
  <%= link_to "<button class=btn btn-success>Cancel</button>".html_safe,main_form_path%>
</div>
<div class="col-sm-3">
</div> 
</div>  

  </div>

<% end %>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
 $("input[type=radio]").click(function () {
debugger;
if ($('#age_type').is(':checked')) { 
      $('#text').show();
    } else {
      $('#text').hide();
    }
});
});
</script>

app/views/users/show.html.erb
<link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
<nav class="navbar navbar-default">
 <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.min.css" integrity="sha256-zV9aQFg2u+n7xs0FTQEhY0zGHSFlwgIu7pivQiwJ38E=" crossorigin="anonymous" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.min.js" integrity="sha256-xoE/2szqaiaaZh7goVyF5p9C/qBu9dM3V5utrQaiJMc=" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
    <div class="container" >
      <div class="navbar-header">
        <a class="navbar-brand" href="#">
          <%= image_tag("logo.png")%><p style="font-family:'Pacifico',cursive;font-size:28px;">Events Schedule</p></a>
        </div>
        <ul class="nav navbar-nav navbar-right">

          <p class="active">
            
            <%= link_to "<button class=btn btn-success ng-click=capture()>Log out</button>".html_safe,log_out_path%>
            
           
            <dir id="user_nav">
             <p style="font-size:18px"><b>logged in as</b></p><%= current_user.username%>
</dir>
 </p>        
</ul>
          

          </div>  
        
      </nav>



</br></br>

  <div style="font-size:18px;">
  
  <div class="container">
  <h1 style="text-align:center">Profile</h1></br>
 <div class="row">
 <div class="col-sm-4">
 </div>
 <div class="col-sm-5">
      <b>First name</b>  <%=@user.firstname%> </br></br>
    <b>Last_name</b>       <%= @user.lastname%></br></br>
    <b>User_name</b>      <%=@user.username%> </br></br>
    <b>Email</b>         <%= @user.email%></br></br>
    <b>Phone_number</b>   <%= @user.phone%></br></br>
<%if current_user.id==@user.id%>
   <%= link_to "<button class=btn btn-success>Edit</button>".html_safe,user_edit_path%>
    <%= link_to "<button class=btn btn-success>Back</button>".html_safe,event_new_path%>
   <%else%>
  <%= link_to "<button class=btn btn-success>Back</button>".html_safe,event_new_path%>
  <%end%>
</div>
<div class="col-sm-3">
</div> 
</div>  

  </div>

app/views/users/show_user.html.erb
<link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
<nav class="navbar navbar-default">
 <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.min.css" integrity="sha256-zV9aQFg2u+n7xs0FTQEhY0zGHSFlwgIu7pivQiwJ38E=" crossorigin="anonymous" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.min.js" integrity="sha256-xoE/2szqaiaaZh7goVyF5p9C/qBu9dM3V5utrQaiJMc=" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
    <div class="container" >
      <div class="navbar-header">
        <a class="navbar-brand" href="#">
          <%= image_tag("logo.png")%><p style="font-family:'Pacifico',cursive;font-size:28px;">Events Schedule</p></a>
        </div>
        <ul class="nav navbar-nav navbar-right">

          <p class="active">
            
            <%= link_to "<button class=btn btn-success ng-click=capture()>Log out</button>".html_safe,log_out_path%>
            
           
            <dir id="user_nav">
             <p style="font-size:18px"><b>logged in as</b></p><%= current_user.username%>
</dir>
 </p>        
</ul>
          

          </div>  
        
      </nav>



</br></br>

  <div style="font-size:18px;">
  
  <div class="container">
  <h1 style="text-align:center">Profile</h1></br>
  <div class="col-md-6">
    <b>User name</b><%=@user.username%> </br></br>
    <b>Last name</b>       <%= @user.lastname%></br></br>
    <b>First name</b>      <%=@user.firstname%> </br></br>
    <b>Email</b>         <%= @user.email%></br></br>
    <b>Phone_number</b>   <%= @user.phone%></br></br>
  <%= link_to "<button class=btn btn-success>Back</button>".html_safe,event_new_path%>
</div>
<div class="col-md-6">
 <%= image_tag @user.image, :style => "width:320px;heigth:320px"%> 
</div>

</div>  

  </div>