config/routes.rb
Rails.application.routes.draw do

  
  ActiveAdmin.routes(self)

  put "/admin/users/:user.id/approve" => 'admin/users#approve', as: :admin_approve_user
  root "users#main_form"
  
  get '/auth/:provider/callback', to: 'sessions#create'

  get 'user/new' => 'users#new', as: :user_new

  post 'user' => 'users#create', as: :user_create
  
  get 'user/form' => 'users#main_form', as: :main_form

  get 'user/login' => 'sessions#new', as: :login_form

  post 'user/login_form' => 'sessions#create', as: :login_create

  get 'user/event_form/:user_id' => 'events#new', as: :event_new

  post 'user/event_create/:user_id' => 'events#create', as: :event_create

  get "event/:user_id/:event_id" => "events#delete", as: :event_destroy

  get 'log_out' => 'events#destroy', as: :log_out

  get 'edit/:user_id/:event_id' => 'events#edit', as: :event_edit

  get 'edit/:event_id' => 'events#show', as: :event_show

  put "edit/:user_id/:event_id" => "events#update", as: :event_update

  get "user/edit/:user_id" => "users#edit" , as: :user_edit

  put 'user/create/:user_id' => 'users#update', as: :user_update

  get 'user/show/:user_id' => 'users#show', as: :user_show

  get '/patient' => 'patients#new', as: :patient_new

  post '/patient' => 'patients#create', as: :patient_create

  get '/patient/:patient_id' => 'patients#show' , as: :patient_show

  post 'comment/create/:event_id' => 'comments#create', as: :comment_create

  get 'change/password/' => 'users#change_password', as: :change_password

  put 'update/password/' => 'users#password_update', as: :password_update

  get 'show/user/:user_id' => 'users#show_user', as: :show_user

end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :invitations
	has_many :invitees, through: :invitations,foreign_key: :invitee_id
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_filter :edit_event
	before_filter :find_user
	include EventsHelper
   	private
	def params_event
		params.require(:event).permit(:event,:venue,:date,:time,:description,:invitee,:status)
	end
	def edit_event

		@event = Event.find_by_id(params[:event_id])
	end

	def find_user
		@user=User.find_by_id(params[:user_id])
	end
end

app/helpers/events_helper.rb
module EventsHelper
	def new
		@event=Event.new
		@users=User.all
		# @events=Event.paginate(:page => params[:page], per_page: 2)
		@events=Event.all
		# binding.pry
		gon.event=@events
		

		# render :json => @events
		# render :json => @eusers

	end

	def create
		
		@event = Event.new(params_event)
		# binding.pry
		@event.user_id=@user.id
	

		@event.save
		params[:role_ids].each do |t|
			@invitation=Invitation.new
			@invitation.event_id=@event.id
			@invitation.invitee_id=t
			@invitation.inviter_id=params[:user_id]
			
		@invitation.save
		end
		redirect_to event_new_path
	end

	def destroy
   	  session[:user_id] = nil
  	  redirect_to root_url, :notice => "Logged out!"
   	end

	def update
   	# binding.pry
   		@event=Event.find_by_id(params[:event_id])
		
		
		params[:role_ids].each do |t|
			@invitation=Invitation.new
			
			@invitation.event_id=@event.id
			@invitation.invitee_id=t
			@invitation.inviter_id=params[:user_id]
			
			
		@invitation.save
		end
		@event.update_attributes(params_event)
		

		redirect_to event_new_path
		
	end
	def show
		@event = Event.find_by_id(params[:event_id])
		@comments=Comment.all
		
	end
   def edit
   	# binding.pry
		@users=User.all
   		# @event=@event_edit
   		@event_edit = @event.id
		@inviter=@event.invitations[0].inviter_id
   		
   		@user=@user.id
   		

   end
   	def delete
		@event = Event.find_by_id(params[:event_id])
		@event.destroy
		redirect_to event_new_path
	end

	

end

app/views/events/edit.html.erb
<link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
<nav class="navbar navbar-default">
  <div class="container" >
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
          <%=image_tag("logo.png")%><p style="font-family:'Pacifico',cursive;font-size:28px;">Events Schedule</p></a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <%if current_user==false%>
     
      <li class="active">
      <li><%= link_to "<button class=btn btn-success>Log out</button>".html_safe,log_out_path%>
      </li>
      <dir id="user_nav">
      <li><p style="font-size:18px"><b>logged in as</b></p><%= current_user.username%>
      </li>

       <%end%>
  </div>
</nav>
</br></br>
 <% if current_user.id == @inviter %>


<%= form_for @event, url:event_edit_path(@user,@event), method: :put do |f|%>

 <%= f.label :Enter_Event_name%>    <%= f.text_field :event %></br></br>
    <%= f.label :Enter_Venue%>       <%= f.text_field :venue %></br></br>
    <%= f.label :Enter_date%>       <%= f.text_field :date %></br></br>
    <%= f.label :Enter_time %>           <%= f.text_field :time %></br></br>
    <%= f.label :Enter_description%>    <%= f.text_area :description, size: "60x5" %></br></br>
    <%= f.label :Invited_by %> </br>    
    <%= current_user.username%> </br>
     </br>
      <%= f.label :Select_invitee %> 
        <ul>
          <% @users.each do |role| %>
           
            <li>
            <%= check_box_tag 'role_ids[]', role.id -%>
            <%= role.username -%>
            </li>
          
          <% end %>
      </ul>

    <%= f.label :Enter_Status%>  
    <%= f.select :status, ['open', 'closed']%></br></br></br>
 <%= f.submit :Submit,:class=>"btn" %>

 <%end%>
 <%else%>
 <%= form_for :event do |f| %>

 <%= f.label :Enter_Event_name%>    <%= f.text_field :event, :disabled => true %></br></br>
    <%= f.label :Enter_Venue%>       <%= f.text_field :venue, :disabled => true %></br></br>
    <%= f.label :Enter_date%>       <%= f.text_field :date, :disabled => true %></br></br>
    <%= f.label :Enter_time %>           <%= f.text_field :time, :disabled => true %></br></br>
    <%= f.label :Enter_description%>    <%= f.text_area :description, size: "60x5", :disabled => true %></br></br>
    <%= f.label :Invited_by %> </br>    
    <%= current_user.username%> </br>
     </br>
    <%= f.label :Invitee %> 

   
                  <%@participant=@event.invitees%>
                  <%@participant.each do |name|%>

                  <p><%=name.username %></p
           
           
          <% end %>
   
    <%= f.label :Enter_Status%>  
    <%= f.select :status, :disabled => true%></br></br></br>
    
 <%= link_to "<button class=btn btn-success>Back</button>".html_safe,event_new_path(@user)%>
 <%end%>

 <%end%>
 

app/views/events/new.html.erb
<%= render 'partials/event'%>
      <%= form_for @event,url: event_create_path do |f| %>

      <div class="container">
        <div class="row">
          <div class="col-sm-6" >
            <dir id="user_nav">
              <select id='purpose'>
<option value="0">Personal use</option>
<option value="1">Business use</option>
<option value="2">Passing on to a client</option>
</select>
<div style='display:none;' id='business'><p>Business Name</p><br/></div>
<div style='display:none;' id='passing'><p>Passing on to a client</p><br/></div>
<div style='display:none;' id='personal'><p>Personal</p><br/></div>
              
              <% @events.each do |event| %> 
        
           
              <div class="row" style="background-color:#D3D3D3; margin:5px; padding:20px">

              <label style="color:green">Event:</label><label><%= event.event %></label><br>
              <label style="color:green">Description: </label>
              <label><%= event.description %></label>        
            </br>  
            <label style="color:green">Organizer: </label>
            <label>
           
             <% u=event.user_id %>
             <%name=User.find_by_id(u) %>
             <%= name.username %>

           </label> </br>   
           <%= link_to "<button class=btn btn-success>Edit</button>".html_safe, event_edit_path(@user,event) %>   

           <%= link_to "<button class=btn btn-success>Distroy</button>".html_safe, event_destroy_path(@user,event) %>
              <%= link_to "<button class=btn btn-success>Post</button>".html_safe,event_show_path(event)%></br></br>
           
           <a  data-toggle="modal" data-target="#myModal2-<%=event.id%>"><button class=btn btn-success>Participants</a></button> <!-- Modal -->

           <div class="modal fade" id="myModal2-<%=event.id%>" role="dialog">
            <div class="modal-dialog">   <!-- Modal content-->
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4 class="modal-title">List of Participants        </h4>
                </div>
                <div class="modal-body">

                  <%@participant=event.invitees%>
                  <%@participant.each do |name|%>

                  <p><%=name.username %></p>


                  <%end%>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
        </div> 
        <% end %>
         
      </div>

      <div class="col-sm-6">
        <b>SEARCH</b><input type="text" ng-model="search1" placeholder="Enter event to be searched" class="form-control">
                <div ng-repeat="event in list | 
             filter:search1">
              <div class="row" style="margin:5px; padding:5px">
              <label style="color:green">Event:</label><label> {{event.event}}</label><br></div></div>
           
             <div class="style">
              <% @events.each do |event| %> 

              <%if current_user.id==event.user_id%>
              <%= link_to "you".html_safe,user_show_path(current_user)%> create the event: <b><%= event.event%></b>  at <%= event.created_at.strftime('%d %b %y %H:%M')%></br>
             and Updated at :  <%=event.updated_at.strftime('%d %b %y %H:%M')%></br></br>
          
              <%else%>
              <% u=event.user_id %>
         
             <%name=User.find_by_id(u) %>
             <%=link_to name.username.html_safe,user_show_path(name) %> created an event: <b><%= event.event%></b> at <%=event.created_at.strftime('%d %b %y %H:%M')%></br>
             and Updated at :  <%=event.updated_at.strftime('%d %b %y %H:%M')%></br></br>
             <%end%>           
             <%end%>
              </div>
             
        <h2>Create event</h2>

        <!-- Trigger the modal with a button -->
        <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Create New event</button>
        <h2>Registerted Users</h2>
            <% @users.each do |f| %>
            <%if f.id!=current_user.id%>
            <b>Name:</b> <%= link_to f.username, show_user_path(f)%></br>
            <%end%>
          <%end%>
        <!-- Modal -->
                <div class="modal fade" id="myModal" role="dialog">
          <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Modal Header</h4>
              </div>
              <div class="modal-body">

                <%= f.label :Enter_Event_name%>    <%= f.text_field :event %></br></br>
                <%= f.label :Enter_Venue%>       <%= f.text_field :venue %></br></br>
                 <p >
                        <%= f.label :date %><br>
                        <%= f.text_field :date, :id => 'datepicker' %>

                      </p>
                      <p >
                        <%= f.label :time %><br>
                        <%= f.text_field :time, :id => 'timepicker' %>


                      </p></br></br>
                <%= f.label :Enter_description%>    <%= f.text_area :description, size: "60x5" %></br></br>
                <%= f.label :Invited_by%>
                <%= current_user.username%><br>
                <%= f.label :Select_invitee %> 
             
                <ul>
                  <% @users.each do |role| %>
                 
                  <li>
                    <%= check_box_tag 'role_ids[]', role.id -%>
                    <%= role.username -%>
                  </li>
                  
                  <% end %>
                </ul>
                <%= f.label :Enter_Status%>  
                <%= f.select :status, ['open', 'closed']%></br></br></br>

              </div>

            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <%= f.submit :Submit,:class=>"btn" %>
            </div>
          </div>
        </div>

      </div>
    </div>

  </div>

  <% end %>

</div>

app/views/events/profile.html.erb
<link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
<nav class="navbar navbar-default">
 <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.min.css" integrity="sha256-zV9aQFg2u+n7xs0FTQEhY0zGHSFlwgIu7pivQiwJ38E=" crossorigin="anonymous" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.min.js" integrity="sha256-xoE/2szqaiaaZh7goVyF5p9C/qBu9dM3V5utrQaiJMc=" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
    <div class="container" >
      <div class="navbar-header">
        <a class="navbar-brand" href="#">
          <%= image_tag("logo.png")%><p style="font-family:'Pacifico',cursive;font-size:28px;">Events Schedule</p></a>
        </div>
        <ul class="nav navbar-nav navbar-right">

          <p class="active">
            
            <%= link_to "<button class=btn btn-success ng-click=capture()>Log out</button>".html_safe,log_out_path%>
            
           
            <dir id="user_nav">
             <p style="font-size:18px"><b>logged in as</b></p><%= current_user.username%>
</dir>
 </p>        
</ul>
          

          </div>  
        
      </nav>

<%= form_for @user, url:user_edit_path(@user,@event), method: :put do |f|%>

</br></br>

  <div style="font-size:18px;">
  
  <div class="container">
  <h1 style="text-align:center">Sign Up</h1></br>
 <div class="row">
 <div class="col-sm-4">
 </div>
 <div class="col-sm-5">
      <%= f.label "Enter First name" %>    <%= f.text_field :firstname , class: "form-control",required: true%></br></br>
    <%= f.label :Enter_Last_name%>       <%= f.text_field :lastname , class: "form-control",:required=>true %></br></br>
    <%= f.label :Enter_User_name%>       <%= f.text_field :username, class: "form-control",:required=>true%></br></br>
    <%= f.label :Enter_valid_Email %>           <%= f.email_field :email, class: "form-control",:required=>true %></br></br>
    <%= f.label :Enter_Ph_number%>    <%= f.text_field :phone,class: "form-control",:required=>true %></br></br>
    <%= f.label :Enter_password %>              <%= f.password_field :password,class: "form-control",:required=>true %></br></br>
      <% if @user.errors.any? %>
    <div class="error_messages">
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.label :password_confirmation %>  <%= f.password_field :password_confirmation,class: "form-control",:required=>true %></br></br>
  <%= f.submit :Submit,:class=>"btn" %>
  <%= link_to "<button class=btn btn-success>Cancel</button>".html_safe,main_form_path%>
</div>
<div class="col-sm-3">
</div> 
</div>  

  </div>

<% end %>

app/views/events/show.html.erb
<link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
<nav class="navbar navbar-default">
 <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.min.css" integrity="sha256-zV9aQFg2u+n7xs0FTQEhY0zGHSFlwgIu7pivQiwJ38E=" crossorigin="anonymous" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.min.js" integrity="sha256-xoE/2szqaiaaZh7goVyF5p9C/qBu9dM3V5utrQaiJMc=" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
  <body>
    <div class="container" >
      <div class="navbar-header">
        <a class="navbar-brand" href="#">
          <%= image_tag("logo.png")%><p style="font-family:'Pacifico',cursive;font-size:28px;">Events Schedule</p></a>
        </div>
        <ul class="nav navbar-nav navbar-right">

          <p class="active">
            
            <%= link_to "<button class=btn btn-success ng-click=capture()>Log out</button>".html_safe,log_out_path%>
            
           
            <dir id="user_nav">
             <p style="font-size:18px"><b>logged in as</b></p><%= current_user.username%>
</dir>
 </p>        
</ul>
          

          </div>  
        
      </nav>



</br></br>

  <div style="font-size:18px;">
  
  <div class="container">
  <h1 style="text-align:center">Event</h1></br>
 <div class="row">

 <div class="col-sm-6" style="font-size:14">
      <b>Event</b>            <%=@event.event%> </br></br>
    <b>Description</b>        <%=@event.description%></br></br>
  
    <b>Organizer</b>  
      <% u=@event.user_id %>
      <%name=User.find_by_id(u) %>
      <%= name.username %> </br></br>
    <b>Date</b>          <%=@event.date%> </br></br>
    <b>Time</b>          <%=@event.time%> </br></br>
    <b>Venue</b>          <%=@event.venue%> </br></br>


<button class="btn clickme">Post</button>
      <%= link_to "<button class=btn btn-success>Back</button>".html_safe,event_new_path(current_user)%></br></br>

      <% @comments.each do |comment| %> 
     

      <%if comment.event_id == @event.id  %>
      <%user = comment.user_id%>
      <%user=User.find(user)%>
      <b><%= user.username%></b>
      <%= comment.description%></br>
      <%end%>
<%end%>

</div>
<div class="hidetext">
<div class="col-sm-6">

      <%= form_for :comment,url: comment_create_path(@event) do |f| %>

      </br></br>

      <b><h4 style="text-align:center">Post Comment</h4></b>
      <%= f.label "Enter Title" %>    <%= f.text_field :title , class: "form-control",required: true%></br>
      <%= f.label :Enter_Description%>       <%= f.text_field :description , class: "form-control",:required=>true %></br>
    
      <%= f.submit :Submit,:class=>"btn" %>
      <%= link_to "<button class=btn btn-success>Cancel</button>".html_safe,event_show_path(@event)%>



<%end%>

  
</div>

</div> 
</div>  

  </div>
<script type="text/javascript" src="//code.jquery.com/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
  <script>
 $(document).ready(function() {
    $(".hidetext").hide();
        $(".clickme").click(function() {
            $(".hidetext").show();
    });
});
  </script>

</body>